<?php
/**
 * *
 *  * @author MagePrakash Wallet
 *  * @copyright Copyright (c) 2020 MagePrakash (https://www.mageprakash.com)
 *  * @package MagePrakash_Wallet
 *
 */
?>

<?php if ($block->getWalletBalance()): ?>
    <tr>
        <td class="label"><strong><?= $block->escapeHtml(__($block->getLabel())); ?></strong></td>
        <td>
            <?= $block->getFormatWalletBalance(); ?>
        </td>
    </tr>
<?php endif; ?>
